---
- name: S1
  loopback: yes
  num: -1
  router: no
  interface:
    - id: 1
      desc: "connect to G0/1 of R1"
    - id: 2
      desc: "connect to G0/1 of R2"
  
- name: R1
  loopback: yes
  num: 0
  router: yes
  interface:
    - id: 1
      ip: 172.31.182.17
      netmask: 255.255.255.240
      desc: "connect to G0/1 of S2"
    - id: 2
      ip: 172.31.182.33
      netmask: 255.255.255.240
      desc: "connect to G0/1 of R3"

- name: R2
  loopback: yes
  num: 1
  router: yes
  interface:
    - id: 1
      ip: 172.31.182.18
      netmask: 255.255.255.240
      desc: "connect to G0/2 of S1"
    - id: 2
      ip: 172.31.182.49
      netmask: 255.255.255.240
      desc: "connect to G0/2 of R3"

- name: R3
  loopback: yes
  num: 2
  router: yes
  interface:
    - id: 1
      ip: 172.31.182.34
      netmask: 255.255.255.240
      desc: "connect to G0/2 of R1"
    - id: 2
      ip: 172.31.182.50
      netmask: 255.255.255.240
      desc: "connect to G0/2 of R2"
    - id: 3
      ip: 172.31.182.65
      netmask: 255.255.255.240
      desc: "connect to G0/1 of S2"

- name: R4
  loopback: yes
  num: 3
  router: yes
  interface:
    - id: 1
      ip: 172.31.182.66
      netmask: 255.255.255.240
      desc: "connect to G0/2 of S2"

- name: S2
  loopback: yes
  num: 4
  router: no
  interface:
    - id: 1
      desc: "connect to G0/3 of R3"
    - id: 2
      desc: "connect to G0/1 of R4"
    - id: 3
      desc: "connect to G0/1 of R5"

- name: R5
  loopback: yes
  num: 5
  router: yes
  interface:
    - id: 1
      ip: 172.31.182.67
      netmask: 255.255.255.240
      desc: "connect to G0/3 of S2"